### ISSUE TITLE
Support for Wildlfy 11

### ISSUE THREAD

**Issue by jopaha** [voxpupuli/puppet-wildfly#230]
Hi,

are there any plans to update the module to support Wildfly 11?

Kind regards

Jo

**Comment by biemond** [comment]
Just checked the code and there are no restrictions in using version 11.  We only check for a version pattern.
I see some changes in the release notes but I did not have the time to test it so let me know what does not work

**Comment by frozen3** [comment]
We've been using this module with WF 11 (and EAP 7.1) without any issues on EL6/EL7 Linux in standalone mode.  There would be a point in the future where some of the classes (ie wildfly::security::ldap_realm) would need updates for converting to Elytron, but for now the legacy mappings work great for us.

**Comment by jairojunior** [comment]
Just a matter of updating the tests and the docs then?

**Comment by frozen3** [comment]
The only issue I had come across relates to changes to the [init script on EL6 systems.](https://github.com/wildfly/wildfly-core/commit/8c82ba3405d7526e96a9951897de3344a0f043d0) The init script now looks for /etc/default/wildfly instead of /etc/default/wildfly.conf

There are two workarounds that i've used to handle this -

Using a custom conf_file for the wildfly::service::conf_file parameter 
or
Include a symlink resource in the puppet profile calling the wildfly class:
file { '/etc/default/wildfly':
  ensure => link,
  target => '/etc/default/wildfly.conf',
}

Note: The workaround is only needed with WF11, EAP 7.1 still uses the .conf file

**Comment by jopaha** [comment]
Thanks. I will test it in the next few days and report back.

**Comment by jairojunior** [comment]
Tests are passing locally with WF11 for major OS'es, just need to check with EL6 as @frozen3 suggested.

**Comment by jopaha** [comment]
Tested on CentOS 7. Encountered no problems.

**Comment by rwaffen** [comment]
Docs updated or will be updated.
Tested with wildfly 23,  al things where working. closing here
